export const ACTION_USER_SIGN_IN = 'ACTION_USER_SIGN_IN'
export const ACTION_USER_SIGN_UP = 'ACTION_USER_SIGN_UP'
export const ACTION_USER_GET_USERS = 'ACTION_USER_GET_USERS'
export const ACTION_USER_LOGOUT = 'ACTION_USER_LOGOUT'
export const ACTION_MESSAGE_GET_MESSAGES = 'ACTION_MESSAGE_GET_MESSAGES'
export const ACTION_MESSAGE_SEND = 'ACTION_MESSAGE_SEND'
export const ACTION_MESSAGE_READ = 'ACTION_MESSAGE_READ'

export const ACTION_ON_USER_LOGGED = 'ACTION_ON_USER_LOGGED'
export const ACTION_ON_USER_LOGOUT = 'ACTION_ON_USER_LOGOUT'
export const ACTION_ON_USER_NEW_USER = 'ACTION_ON_USER_NEW_USER'
export const ACTION_ON_MESSAGE_READED = 'ACTION_ON_MESSAGE_READED'
export const ACTION_ON_MESSAGE_RECEIVE = 'ACTION_ON_MESSAGE_RECEIVE'

export const ACTION_SET_INTERLOCUTOR = 'ACTION_SET_INTERLOCUTOR'

export const GETTER_INTERLOCUTOR_MESSAGES = 'GETTER_INTERLOCUTOR_MESSAGES'